### ISSUE TITLE
No working after 195 update?

### ISSUE THREAD

**Issue by drakray** [cstahlhut/DailyNeedsMk5#15]
I just found out I can try mk5, so I gave it a try.
I got some emergency water and food on me from dropPod, but I don't seem to be consuming them, and I don't have HUD info about needs like in mk4.
[SpaceEngineers_20200628_130246233.log](https://github.com/cstahlhut/DailyNeedsMk5/files/4843004/SpaceEngineers_20200628_130246233.log) if it can help maybe

**Comment by dikkeduif** [comment]
Thanks for the logs @drakray, it was also not working for me after latest update. I will merge this, but think this might be a temporary fix.
