### ISSUE TITLE
Exhaustion and Cryo Pod

### ISSUE THREAD

**Issue by tbene7** [cstahlhut/DailyNeedsMk5#17]
If you enter a cryopod while exhaustion is in the red or yellow, it keeps declining and you loose hp. Not entirely sure if this is intentional, cryo pods should at least have the same effect as cockpits.

**Comment by cstahlhut** [comment]
Fixed. Was an issue with 
`// Assign sounds emitter and play relevant heartbeat sounds based on fatigue.
                        soundEmitter.Entity = (MyEntity) controlledEnt;
                        if (playerData.fatigue < (MAX_NEEDS_VALUE / 4) && playerData.fatigue > 0.0f &&
                            (playerData.fatigue - 1) > playerData.fatigue)
                        {
                            if (!fatigueRecoverySoundPlayed)
                            {
                                soundEmitter.PlaySound(FASTHEARTWITHBEEP_SOUND_FADEOUT);
                                fatigueRecoverySoundPlayed = true;
                            }
                        }
                        else if (playerData.fatigue <= 0.0f)
                        {
                            fatigueRecoverySoundPlayed = false;
                            //soundEmitter.VolumeMultiplier = Math.Max(1.0f, Math.Abs(playerData.fatigue / 100));
                            soundEmitter.PlaySound(FASTHEARTWITHBEEP_SOUND);

                        }`

Stupidly used a playerData.fatigue-- which was overcoming minimal positive value used in a cryo.
