### ISSUE TITLE
Kitchen mini showing big block when building, turns into small block when finished

### ISSUE THREAD

**Issue by dikkeduif** [cstahlhut/DailyNeedsMk5#6]
When trying to build the mini kitchen, the progress blocks are big. When it's finished it's a small block.

I think it's a config issue in Kitchen_CubeBlocks_Small_Ship.sbc

```
<Model BuildPercentUpperBound="0.33" File="Models\Cubes\Small\Kitchen_Small_Constr1.mwm" />
<Model BuildPercentUpperBound="0.66" File="Models\Cubes\Small\Kitchen_Small_Constr2.mwm" />
<Model BuildPercentUpperBound="1.00" File="Models\Cubes\Small\Kitchen_Small_Constr3.mwm" />
```

Should be

```
<Model BuildPercentUpperBound="0.33" File="Models\Cubes\Small\Kitchen_Mini_Small_Constr1.mwm" />
<Model BuildPercentUpperBound="0.66" File="Models\Cubes\Small\Kitchen_Mini_Small_Constr2.mwm" />
<Model BuildPercentUpperBound="1.00" File="Models\Cubes\Small\Kitchen_Mini_Small_Constr3.mwm" />
```

Also when the block is finished it seems to throw an error from MoveLeftArm, MoveRightArm and RotateCutter. The given key was not present in the dictionary.

**Comment by dikkeduif** [comment]
Fixed

**Comment by cstahlhut** [comment]
Fixed in https://github.com/cstahlhut/DailyNeedsMk5/commit/66a1b0aaeb2f22563bc669e5f386f27a87fe43f5
